### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by Shramkoweb** [SmartRW/gulp-html-css-js-boilerplate#1]
У тебя старт собирает проект и потом следит за всеми файлами проекта.
Но при этом, после остановки сервера и его перезапуска будет каждый раз запускаться build, а в нем идет оптимизация графики.
На мой взгляд оптимально будет делать какойло легковестный билд без графики.
А отдельно делать таск Deploy , в котором уже будет полностью вся оптимизация.

**Comment by SmartRW** [comment]
Разделил режим разработки и режим релиза, описание добавил в ридми.
